name: ci.yml
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and project
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: pnpm install
      - name: Run lint on all services
        run: pnpm lint
      - name: Run prettier check on all services
        run: pnpm run format:check
      - name: Run build for all services
        run: pnpm build
      - name: run tests for all services
        run: pnpm test
